version: '3'

services:
  frontend:
    build: 
      context: ./frontend-app
    ports:
      - "8001:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend-app
    ports:
      - "8000:8000"

